In [1]:
import tensorflow as tf 
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [2]:
##load the model and pickle file
model = load_model('model.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_gender = pickle.load(file)
    
with open('onehot_encoder_geo.pkl','rb') as file:
    ohe = pickle.load(file)
    
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [5]:
type(input_data)

dict

In [8]:
geo_encoded = ohe.transform([[input_data['Geography']]])
geo_encoder_df = pd.DataFrame(geo_encoded,columns=ohe.get_feature_names_out(['Geography']))
geo_encoder_df

c:\Users\karti\anaconda3\envs\ann_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [11]:
input_df=pd.DataFrame([input_data])
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_encoder_df], axis=1)

In [14]:
input_df['Gender'] = label_gender.transform(input_df['Gender'])

In [15]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [16]:
##scaile the input data
input_scaled = scaler.transform(input_df)

In [17]:
model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

array([[0.01132811]], dtype=float32)